# Generated by Django 6.0 on 2025-12-31 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JenisBerkas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.SlugField(max_length=30, unique=True)),
                ("nama", models.CharField(max_length=100)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("wajib", models.BooleanField(default=True)),
                ("aktif", models.BooleanField(default=True)),
                ("urutan", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name_plural": "Jenis Berkas",
                "ordering": ["urutan", "nama"],
            },
        ),
        migrations.CreateModel(
            name="Jurusan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100, unique=True)),
                ("keterangan", models.TextField(blank=True, null=True)),
                ("aktif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Jurusan",
            },
        ),
        migrations.CreateModel(
            name="KabupatenKota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=10)),
                ("nama", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name_plural": "Kabupaten Kota",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="Negara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kode",
                    models.CharField(
                        help_text="Kode ISO-3166-1 alpha-3 (misal: IDN)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("nama", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Negara",
                "ordering": ["nama"],
            },
        ),
        migrations.CreateModel(
            name="TahunAkademik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=20, unique=True)),
                ("mulai", models.DateField()),
                ("selesai", models.DateField()),
                ("aktif", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Tahun Akademik",
                "ordering": ["-mulai"],
            },
        ),
        migrations.CreateModel(
            name="Wali",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=120)),
                (
                    "hubungan",
                    models.CharField(
                        help_text="Hubungan: Ayah/Ibu/Wali", max_length=50
                    ),
                ),
                ("pekerjaan", models.CharField(blank=True, max_length=100, null=True)),
                ("no_hp", models.CharField(blank=True, max_length=20, null=True)),
                ("alamat", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Wali",
            },
        ),
        migrations.CreateModel(
            name="Kecamatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=10)),
                ("nama", models.CharField(max_length=120)),
                (
                    "kabupaten",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kecamatan",
                        to="zainul.kabupatenkota",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kecamatan",
                "ordering": ["nama"],
                "unique_together": {("kabupaten", "nama")},
            },
        ),
        migrations.CreateModel(
            name="DesaKelurahan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=10)),
                ("nama", models.CharField(max_length=120)),
                (
                    "kecamatan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desa",
                        to="zainul.kecamatan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Desa Kelurahan",
                "ordering": ["nama"],
                "unique_together": {("kecamatan", "nama")},
            },
        ),
        migrations.CreateModel(
            name="Provinsi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=10)),
                ("nama", models.CharField(max_length=100)),
                (
                    "negara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provinsi",
                        to="zainul.negara",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Provinsi",
                "ordering": ["nama"],
                "unique_together": {("negara", "nama")},
            },
        ),
        migrations.AddField(
            model_name="kabupatenkota",
            name="provinsi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kabupaten",
                to="zainul.provinsi",
            ),
        ),
        migrations.CreateModel(
            name="Siswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=120)),
                ("nisn", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("tanggal_daftar", models.DateField(default=django.utils.timezone.now)),
                ("foto", models.ImageField(blank=True, upload_to="gambar/foto")),
                ("nik", models.CharField(max_length=20, unique=True)),
                ("tempat_lahir", models.CharField(max_length=100)),
                ("tanggal_lahir", models.DateField()),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
                    ),
                ),
                (
                    "agama",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Islam", "Islam"),
                            ("Kristen", "Kristen"),
                            ("Hindu", "Hindu"),
                            ("Budha", "Budha"),
                            ("Kongucu", "Kongucu"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status_pendaftaran",
                    models.CharField(
                        choices=[
                            ("DAFTAR", "Terdaftar"),
                            ("VERIFIKASI", "Terverifikasi"),
                            ("DITOLAK", "Ditolak"),
                        ],
                        default="DAFTAR",
                        max_length=20,
                    ),
                ),
                (
                    "alamat_detail",
                    models.CharField(
                        blank=True,
                        help_text="Nama jalan, RT/RW, nomor rumah, dll.",
                        max_length=255,
                    ),
                ),
                (
                    "desa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="siswa",
                        to="zainul.desakelurahan",
                    ),
                ),
                (
                    "jurusan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="siswa",
                        to="zainul.jurusan",
                    ),
                ),
                (
                    "kabupaten",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="siswa",
                        to="zainul.kabupatenkota",
                    ),
                ),
                (
                    "kecamatan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="siswa",
                        to="zainul.kecamatan",
                    ),
                ),
                (
                    "negara",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="siswa",
                        to="zainul.negara",
                    ),
                ),
                (
                    "provinsi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="siswa",
                        to="zainul.provinsi",
                    ),
                ),
                (
                    "tahun_akademik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="siswa",
                        to="zainul.tahunakademik",
                    ),
                ),
                (
                    "wali",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anak",
                        to="zainul.wali",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Siswa",
                "ordering": ["nama"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="kabupatenkota",
            unique_together={("provinsi", "nama")},
        ),
        migrations.CreateModel(
            name="Berkas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="berkas_siswa/")),
                ("keterangan", models.TextField(blank=True, null=True)),
                ("tanggal_upload", models.DateTimeField(auto_now_add=True)),
                ("diverifikasi", models.BooleanField(default=False)),
                (
                    "jenis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unggahan",
                        to="zainul.jenisberkas",
                    ),
                ),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="berkas",
                        to="zainul.siswa",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Berkas",
                "ordering": ["-tanggal_upload"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("siswa", "jenis"), name="uniq_berkas_per_siswa_jenis"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="siswa",
            index=models.Index(
                fields=["negara", "provinsi", "kabupaten", "kecamatan", "desa"],
                name="zainul_sisw_negara__8eb01a_idx",
            ),
        ),
    ]
