# Generated by Django 6.0 on 2026-01-12 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zainul", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siswa",
            name="tanggal_daftar",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
