# Generated by Django 6.0 on 2026-01-21 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zainul", "0002_alter_siswa_tanggal_daftar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="siswa",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Akun login untuk pendaftar",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="siswa",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
